language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - 1.8.7
gemfile:
  - gemfiles/Gemfile.rspec2
  - gemfiles/Gemfile.rspec3-0
  - gemfiles/Gemfile.rspec3-1
script: bundle exec rspec
